name: task_tracker_app
description: "A voice-driven task tracker app with AI-powered task parsing and offline-first architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.6
  phosphor_flutter: ^2.1.0
  flutter_slidable: ^4.0.1
  fl_chart: ^1.0.0
  # font_awesome_flutter: ^10.1.0  # Temporarily disabled due to compatibility issues

  # State Management
  flutter_riverpod: ^2.6.1

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Database
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3

  # JSON Serialization
  json_annotation: ^4.9.0

  # Speech Recognition and Audio
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  flutter_sound: ^9.2.13
  just_audio: ^0.10.4
  ffmpeg_kit_flutter_new: ^3.2.0
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # File handling
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  share_plus: ^11.1.0
  csv: ^5.0.2
  crypto: ^3.0.3
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # Enterprise Export/Import
  excel: ^4.0.6
  archive: ^3.6.1
  xml: ^6.5.0
  html: ^0.15.4
  markdown: ^7.2.2
  
  # Cloud Storage Integration
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # Advanced Charts and Reporting
  syncfusion_flutter_charts: ^30.2.6
  syncfusion_flutter_xlsio: ^30.2.6
  syncfusion_flutter_pdf: ^30.2.6
  
  # Calendar
  syncfusion_flutter_calendar: ^30.2.6
  
  # Share intent and external app integration
  url_launcher: ^6.2.1
  android_intent_plus: ^5.3.1
  mailer: ^6.0.1
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Authentication
  local_auth: ^2.1.7
  
  # Calendar Integration
  device_calendar: ^4.3.3
  
  # Cloud Services
  supabase_flutter: ^2.9.1
  
  # Connectivity
  connectivity_plus: ^6.1.5
  
  # Timezone
  timezone: ^0.10.0
  receive_sharing_intent: ^1.8.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Sharing (already declared above)

  riverpod_annotation: any
  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  riverpod_generator: ^2.6.1
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.2
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter

  tasky: any
dependency_overrides:
  timezone: ^0.10.0
  flutter_local_notifications: ^19.4.0
  archive: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # Local fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono[wght].ttf
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-VariableFont_wdth,wght.ttf
    - family: Sansation
      fonts:
        - asset: assets/fonts/Sansation-Regular.ttf
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-VariableFont_wght.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf    
