name: task_tracker_app
description: "A voice-driven task tracker app with AI-powered task parsing and offline-first architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  phosphor_flutter: ^2.1.0
  # font_awesome_flutter: ^10.1.0  # Temporarily disabled due to compatibility issues

  # State Management
  flutter_riverpod: ^2.6.0

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.1
  path: ^1.8.3

  # JSON Serialization
  json_annotation: ^4.9.0

  # Speech Recognition and Audio
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.1
  flutter_sound: ^9.2.13
  just_audio: ^0.9.36
  ffmpeg_kit_flutter_new: ^3.2.0
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # File handling
  file_picker: ^10.0.0
  share_plus: ^7.2.1
  csv: ^5.0.2
  crypto: ^3.0.3
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Share intent and external app integration
  url_launcher: ^6.2.1
  android_intent_plus: ^4.0.3
  mailer: ^6.0.1
  
  # Notifications
  flutter_local_notifications: ^19.0.0
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Authentication
  local_auth: ^2.1.7
  sign_in_with_apple: ^7.0.1
  
  # Calendar Integration
  device_calendar: ^4.3.3
  
  # Cloud Services
  supabase_flutter: ^2.9.1
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Timezone
  timezone: ^0.10.0
  receive_sharing_intent: 1.8.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Sharing (already declared above)

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  riverpod_generator: ^2.6.0
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

dependency_overrides:
  timezone: ^0.10.0
  flutter_local_notifications: ^19.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/backgrounds/
    - assets/backgrounds/matrix/
    - assets/backgrounds/vegeta/
    - assets/backgrounds/dracula/
    - assets/backgrounds/expressive/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
