// Mocks generated by Mockito 5.4.5 from annotations
// in task_tracker_app/test/services/speech/voice_command_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:task_tracker_app/domain/entities/task_enums.dart' as _i8;
import 'package:task_tracker_app/domain/entities/task_model.dart' as _i7;
import 'package:task_tracker_app/domain/repositories/task_repository.dart'
    as _i6;
import 'package:task_tracker_app/services/speech/speech_service.dart' as _i4;
import 'package:task_tracker_app/services/speech/transcription_service.dart'
    as _i2;
import 'package:task_tracker_app/services/speech/voice_command_customization.dart'
    as _i9;
import 'package:task_tracker_app/services/speech/voice_command_models.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTranscriptionConfig_0 extends _i1.SmartFake
    implements _i2.TranscriptionConfig {
  _FakeTranscriptionConfig_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTranscriptionResult_1 extends _i1.SmartFake
    implements _i2.TranscriptionResult {
  _FakeTranscriptionResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoiceCommandConfig_2 extends _i1.SmartFake
    implements _i3.VoiceCommandConfig {
  _FakeVoiceCommandConfig_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i4.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable => (super.noSuchMethod(
        Invocation.getter(#isAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i2.TranscriptionConfig get transcriptionConfig => (super.noSuchMethod(
        Invocation.getter(#transcriptionConfig),
        returnValue: _FakeTranscriptionConfig_0(
          this,
          Invocation.getter(#transcriptionConfig),
        ),
      ) as _i2.TranscriptionConfig);

  @override
  _i5.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> startListening({
    required dynamic Function(String)? onResult,
    required dynamic Function(String)? onError,
    String? localeId,
    Duration? listenFor,
    Duration? pauseFor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
          {
            #onResult: onResult,
            #onError: onError,
            #localeId: localeId,
            #listenFor: listenFor,
            #pauseFor: pauseFor,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancel() => (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> getAvailableLocales() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableLocales,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.TranscriptionResult> transcribeAudioFile(
          String? audioFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeAudioFile,
          [audioFilePath],
        ),
        returnValue: _i5.Future<_i2.TranscriptionResult>.value(
            _FakeTranscriptionResult_1(
          this,
          Invocation.method(
            #transcribeAudioFile,
            [audioFilePath],
          ),
        )),
      ) as _i5.Future<_i2.TranscriptionResult>);

  @override
  _i5.Future<_i2.TranscriptionResult> transcribeAudioData(
          List<int>? audioData) =>
      (super.noSuchMethod(
        Invocation.method(
          #transcribeAudioData,
          [audioData],
        ),
        returnValue: _i5.Future<_i2.TranscriptionResult>.value(
            _FakeTranscriptionResult_1(
          this,
          Invocation.method(
            #transcribeAudioData,
            [audioData],
          ),
        )),
      ) as _i5.Future<_i2.TranscriptionResult>);

  @override
  _i5.Future<void> updateTranscriptionConfig(_i2.TranscriptionConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTranscriptionConfig,
          [config],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i6.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i7.TaskModel>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<_i7.TaskModel?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i5.Future<_i7.TaskModel?>.value(),
      ) as _i5.Future<_i7.TaskModel?>);

  @override
  _i5.Future<void> createTask(_i7.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #createTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateTask(_i7.TaskModel? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.TaskModel>> getTasksByStatus(_i8.TaskStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByStatus,
          [status],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> getTasksByPriority(
          _i8.TaskPriority? priority) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByPriority,
          [priority],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> getTasksDueToday() => (super.noSuchMethod(
        Invocation.method(
          #getTasksDueToday,
          [],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> getOverdueTasks() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> getTasksByProject(String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByProject,
          [projectId],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> searchTasks(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTasks,
          [query],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Future<List<_i7.TaskModel>> getTasksWithFilter(_i6.TaskFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksWithFilter,
          [filter],
        ),
        returnValue: _i5.Future<List<_i7.TaskModel>>.value(<_i7.TaskModel>[]),
      ) as _i5.Future<List<_i7.TaskModel>>);

  @override
  _i5.Stream<List<_i7.TaskModel>> watchAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchAllTasks,
          [],
        ),
        returnValue: _i5.Stream<List<_i7.TaskModel>>.empty(),
      ) as _i5.Stream<List<_i7.TaskModel>>);

  @override
  _i5.Stream<List<_i7.TaskModel>> watchTasksByStatus(_i8.TaskStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasksByStatus,
          [status],
        ),
        returnValue: _i5.Stream<List<_i7.TaskModel>>.empty(),
      ) as _i5.Stream<List<_i7.TaskModel>>);

  @override
  _i5.Stream<List<_i7.TaskModel>> watchTasksByProject(String? projectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTasksByProject,
          [projectId],
        ),
        returnValue: _i5.Stream<List<_i7.TaskModel>>.empty(),
      ) as _i5.Stream<List<_i7.TaskModel>>);
}

/// A class which mocks [VoiceCommandCustomization].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceCommandCustomization extends _i1.Mock
    implements _i9.VoiceCommandCustomization {
  MockVoiceCommandCustomization() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.VoiceCommandConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _FakeVoiceCommandConfig_2(
          this,
          Invocation.getter(#config),
        ),
      ) as _i3.VoiceCommandConfig);

  @override
  Map<String, _i9.CustomVoiceCommand> get customCommands => (super.noSuchMethod(
        Invocation.getter(#customCommands),
        returnValue: <String, _i9.CustomVoiceCommand>{},
      ) as Map<String, _i9.CustomVoiceCommand>);

  @override
  Map<String, String> get commandAliases => (super.noSuchMethod(
        Invocation.getter(#commandAliases),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCustomCommand(_i9.CustomVoiceCommand? command) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCustomCommand,
          [command],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCustomCommand(String? commandId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeCustomCommand,
          [commandId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateCustomCommand(_i9.CustomVoiceCommand? command) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomCommand,
          [command],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addCommandAlias(
    String? alias,
    String? originalCommand,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCommandAlias,
          [
            alias,
            originalCommand,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeCommandAlias(String? alias) => (super.noSuchMethod(
        Invocation.method(
          #removeCommandAlias,
          [alias],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateConfig(_i3.VoiceCommandConfig? newConfig) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfig,
          [newConfig],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getCommandSuggestions(String? transcription) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCommandSuggestions,
          [transcription],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  String exportCustomizations() => (super.noSuchMethod(
        Invocation.method(
          #exportCustomizations,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportCustomizations,
            [],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> importCustomizations(String? jsonData) =>
      (super.noSuchMethod(
        Invocation.method(
          #importCustomizations,
          [jsonData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, int> getCommandUsageStats() => (super.noSuchMethod(
        Invocation.method(
          #getCommandUsageStats,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  bool validateCommandPattern(String? pattern) => (super.noSuchMethod(
        Invocation.method(
          #validateCommandPattern,
          [pattern],
        ),
        returnValue: false,
      ) as bool);
}
