// Mocks generated by Mockito 5.4.5 from annotations
// in task_tracker_app/test/presentation/providers/analytics_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:drift/drift.dart' as _i7;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:task_tracker_app/services/analytics/analytics_models.dart'
    as _i2;
import 'package:task_tracker_app/services/analytics/analytics_service.dart'
    as _i11;
import 'package:task_tracker_app/services/database/daos/project_dao.dart'
    as _i4;
import 'package:task_tracker_app/services/database/daos/tag_dao.dart' as _i5;
import 'package:task_tracker_app/services/database/daos/task_dao.dart' as _i3;
import 'package:task_tracker_app/services/database/daos/task_template_dao.dart'
    as _i6;
import 'package:task_tracker_app/services/database/database.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalyticsSummary_0 extends _i1.SmartFake
    implements _i2.AnalyticsSummary {
  _FakeAnalyticsSummary_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductivityMetrics_1 extends _i1.SmartFake
    implements _i2.ProductivityMetrics {
  _FakeProductivityMetrics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakInfo_2 extends _i1.SmartFake implements _i2.StreakInfo {
  _FakeStreakInfo_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductivityPatterns_3 extends _i1.SmartFake
    implements _i2.ProductivityPatterns {
  _FakeProductivityPatterns_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeakHoursAnalysis_4 extends _i1.SmartFake
    implements _i2.PeakHoursAnalysis {
  _FakePeakHoursAnalysis_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdvancedCategoryAnalytics_5 extends _i1.SmartFake
    implements _i2.AdvancedCategoryAnalytics {
  _FakeAdvancedCategoryAnalytics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductivityInsights_6 extends _i1.SmartFake
    implements _i2.ProductivityInsights {
  _FakeProductivityInsights_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskDao_7 extends _i1.SmartFake implements _i3.TaskDao {
  _FakeTaskDao_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProjectDao_8 extends _i1.SmartFake implements _i4.ProjectDao {
  _FakeProjectDao_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagDao_9 extends _i1.SmartFake implements _i5.TagDao {
  _FakeTagDao_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTaskTemplateDao_10 extends _i1.SmartFake
    implements _i6.TaskTemplateDao {
  _FakeTaskTemplateDao_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_11 extends _i1.SmartFake
    implements _i7.MigrationStrategy {
  _FakeMigrationStrategy_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProjectsTable_12 extends _i1.SmartFake
    implements _i8.$ProjectsTable {
  _Fake$ProjectsTable_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TasksTable_13 extends _i1.SmartFake implements _i8.$TasksTable {
  _Fake$TasksTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SubTasksTable_14 extends _i1.SmartFake
    implements _i8.$SubTasksTable {
  _Fake$SubTasksTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TagsTable_15 extends _i1.SmartFake implements _i8.$TagsTable {
  _Fake$TagsTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TaskTagsTable_16 extends _i1.SmartFake
    implements _i8.$TaskTagsTable {
  _Fake$TaskTagsTable_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TaskDependenciesTable_17 extends _i1.SmartFake
    implements _i8.$TaskDependenciesTable {
  _Fake$TaskDependenciesTable_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TaskTemplatesTable_18 extends _i1.SmartFake
    implements _i8.$TaskTemplatesTable {
  _Fake$TaskTemplatesTable_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_19 extends _i1.SmartFake
    implements _i8.$AppDatabaseManager {
  _Fake$AppDatabaseManager_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_20 extends _i1.SmartFake
    implements _i7.GeneratedDatabase {
  _FakeGeneratedDatabase_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_21 extends _i1.SmartFake
    implements _i7.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_22 extends _i1.SmartFake
    implements _i7.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_23 extends _i1.SmartFake
    implements _i7.DatabaseConnection {
  _FakeDatabaseConnection_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_24 extends _i1.SmartFake implements _i7.QueryExecutor {
  _FakeQueryExecutor_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_25 extends _i1.SmartFake
    implements _i9.StreamQueryStore {
  _FakeStreamQueryStore_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_26 extends _i1.SmartFake
    implements _i7.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_27 extends _i1.SmartFake implements _i7.Migrator {
  _FakeMigrator_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_28<T1> extends _i1.SmartFake implements _i10.Future<T1> {
  _FakeFuture_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_29<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.InsertStatement<T1, D1> {
  _FakeInsertStatement_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_30<T extends _i7.Table, D> extends _i1.SmartFake
    implements _i7.UpdateStatement<T, D> {
  _FakeUpdateStatement_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_31<T1 extends _i7.HasResultSet, D>
    extends _i1.SmartFake implements _i7.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_32<FirstT extends _i7.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i7.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_33<T> extends _i1.SmartFake implements _i7.Selectable<T> {
  _FakeSelectable_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_34<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_35 extends _i1.SmartFake
    implements _i7.GenerationContext {
  _FakeGenerationContext_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i11.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.AnalyticsSummary> getAnalyticsSummary(
    _i2.AnalyticsTimePeriod? period, {
    _i2.DateRange? customRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsSummary,
          [period],
          {#customRange: customRange},
        ),
        returnValue:
            _i10.Future<_i2.AnalyticsSummary>.value(_FakeAnalyticsSummary_0(
          this,
          Invocation.method(
            #getAnalyticsSummary,
            [period],
            {#customRange: customRange},
          ),
        )),
      ) as _i10.Future<_i2.AnalyticsSummary>);

  @override
  _i10.Future<_i2.ProductivityMetrics> getProductivityMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductivityMetrics,
          [],
        ),
        returnValue: _i10.Future<_i2.ProductivityMetrics>.value(
            _FakeProductivityMetrics_1(
          this,
          Invocation.method(
            #getProductivityMetrics,
            [],
          ),
        )),
      ) as _i10.Future<_i2.ProductivityMetrics>);

  @override
  _i10.Future<_i2.StreakInfo> getStreakInfo() => (super.noSuchMethod(
        Invocation.method(
          #getStreakInfo,
          [],
        ),
        returnValue: _i10.Future<_i2.StreakInfo>.value(_FakeStreakInfo_2(
          this,
          Invocation.method(
            #getStreakInfo,
            [],
          ),
        )),
      ) as _i10.Future<_i2.StreakInfo>);

  @override
  _i10.Future<List<_i2.CategoryAnalytics>> getCategoryAnalytics(
    _i2.AnalyticsTimePeriod? period, {
    _i2.DateRange? customRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryAnalytics,
          [period],
          {#customRange: customRange},
        ),
        returnValue: _i10.Future<List<_i2.CategoryAnalytics>>.value(
            <_i2.CategoryAnalytics>[]),
      ) as _i10.Future<List<_i2.CategoryAnalytics>>);

  @override
  _i10.Future<List<_i2.DailyStats>> getDailyStats(_i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyStats,
          [dateRange],
        ),
        returnValue:
            _i10.Future<List<_i2.DailyStats>>.value(<_i2.DailyStats>[]),
      ) as _i10.Future<List<_i2.DailyStats>>);

  @override
  _i10.Future<Map<int, int>> getHourlyProductivity(_i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyProductivity,
          [dateRange],
        ),
        returnValue: _i10.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i10.Future<Map<int, int>>);

  @override
  _i10.Future<Map<int, int>> getWeekdayProductivity(_i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeekdayProductivity,
          [dateRange],
        ),
        returnValue: _i10.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i10.Future<Map<int, int>>);

  @override
  _i10.Future<List<double>> getCompletionRateTrend(
    _i2.DateRange? dateRange,
    int? intervalDays,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletionRateTrend,
          [
            dateRange,
            intervalDays,
          ],
        ),
        returnValue: _i10.Future<List<double>>.value(<double>[]),
      ) as _i10.Future<List<double>>);

  @override
  _i10.Future<void> updateStreakOnTaskCompletion(DateTime? completionDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStreakOnTaskCompletion,
          [completionDate],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> recalculateAnalytics() => (super.noSuchMethod(
        Invocation.method(
          #recalculateAnalytics,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i2.ProductivityPatterns> getProductivityPatterns(
          _i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductivityPatterns,
          [dateRange],
        ),
        returnValue: _i10.Future<_i2.ProductivityPatterns>.value(
            _FakeProductivityPatterns_3(
          this,
          Invocation.method(
            #getProductivityPatterns,
            [dateRange],
          ),
        )),
      ) as _i10.Future<_i2.ProductivityPatterns>);

  @override
  _i10.Future<_i2.PeakHoursAnalysis> getPeakHoursAnalysis(
          _i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeakHoursAnalysis,
          [dateRange],
        ),
        returnValue:
            _i10.Future<_i2.PeakHoursAnalysis>.value(_FakePeakHoursAnalysis_4(
          this,
          Invocation.method(
            #getPeakHoursAnalysis,
            [dateRange],
          ),
        )),
      ) as _i10.Future<_i2.PeakHoursAnalysis>);

  @override
  _i10.Future<_i2.AdvancedCategoryAnalytics> getAdvancedCategoryAnalytics(
    _i2.AnalyticsTimePeriod? period, {
    _i2.DateRange? customRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdvancedCategoryAnalytics,
          [period],
          {#customRange: customRange},
        ),
        returnValue: _i10.Future<_i2.AdvancedCategoryAnalytics>.value(
            _FakeAdvancedCategoryAnalytics_5(
          this,
          Invocation.method(
            #getAdvancedCategoryAnalytics,
            [period],
            {#customRange: customRange},
          ),
        )),
      ) as _i10.Future<_i2.AdvancedCategoryAnalytics>);

  @override
  _i10.Future<String> exportAnalytics(
    _i2.AnalyticsExportFormat? format,
    _i2.AnalyticsTimePeriod? period, {
    _i2.DateRange? customRange,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAnalytics,
          [
            format,
            period,
          ],
          {#customRange: customRange},
        ),
        returnValue: _i10.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #exportAnalytics,
            [
              format,
              period,
            ],
            {#customRange: customRange},
          ),
        )),
      ) as _i10.Future<String>);

  @override
  _i10.Future<_i2.ProductivityInsights> getProductivityInsights(
          _i2.DateRange? dateRange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductivityInsights,
          [dateRange],
        ),
        returnValue: _i10.Future<_i2.ProductivityInsights>.value(
            _FakeProductivityInsights_6(
          this,
          Invocation.method(
            #getProductivityInsights,
            [dateRange],
          ),
        )),
      ) as _i10.Future<_i2.ProductivityInsights>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i8.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskDao get taskDao => (super.noSuchMethod(
        Invocation.getter(#taskDao),
        returnValue: _FakeTaskDao_7(
          this,
          Invocation.getter(#taskDao),
        ),
      ) as _i3.TaskDao);

  @override
  _i4.ProjectDao get projectDao => (super.noSuchMethod(
        Invocation.getter(#projectDao),
        returnValue: _FakeProjectDao_8(
          this,
          Invocation.getter(#projectDao),
        ),
      ) as _i4.ProjectDao);

  @override
  _i5.TagDao get tagDao => (super.noSuchMethod(
        Invocation.getter(#tagDao),
        returnValue: _FakeTagDao_9(
          this,
          Invocation.getter(#tagDao),
        ),
      ) as _i5.TagDao);

  @override
  _i6.TaskTemplateDao get taskTemplateDao => (super.noSuchMethod(
        Invocation.getter(#taskTemplateDao),
        returnValue: _FakeTaskTemplateDao_10(
          this,
          Invocation.getter(#taskTemplateDao),
        ),
      ) as _i6.TaskTemplateDao);

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i7.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_11(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i7.MigrationStrategy);

  @override
  _i8.$ProjectsTable get projects => (super.noSuchMethod(
        Invocation.getter(#projects),
        returnValue: _Fake$ProjectsTable_12(
          this,
          Invocation.getter(#projects),
        ),
      ) as _i8.$ProjectsTable);

  @override
  _i8.$TasksTable get tasks => (super.noSuchMethod(
        Invocation.getter(#tasks),
        returnValue: _Fake$TasksTable_13(
          this,
          Invocation.getter(#tasks),
        ),
      ) as _i8.$TasksTable);

  @override
  _i8.$SubTasksTable get subTasks => (super.noSuchMethod(
        Invocation.getter(#subTasks),
        returnValue: _Fake$SubTasksTable_14(
          this,
          Invocation.getter(#subTasks),
        ),
      ) as _i8.$SubTasksTable);

  @override
  _i8.$TagsTable get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: _Fake$TagsTable_15(
          this,
          Invocation.getter(#tags),
        ),
      ) as _i8.$TagsTable);

  @override
  _i8.$TaskTagsTable get taskTags => (super.noSuchMethod(
        Invocation.getter(#taskTags),
        returnValue: _Fake$TaskTagsTable_16(
          this,
          Invocation.getter(#taskTags),
        ),
      ) as _i8.$TaskTagsTable);

  @override
  _i8.$TaskDependenciesTable get taskDependencies => (super.noSuchMethod(
        Invocation.getter(#taskDependencies),
        returnValue: _Fake$TaskDependenciesTable_17(
          this,
          Invocation.getter(#taskDependencies),
        ),
      ) as _i8.$TaskDependenciesTable);

  @override
  _i8.$TaskTemplatesTable get taskTemplates => (super.noSuchMethod(
        Invocation.getter(#taskTemplates),
        returnValue: _Fake$TaskTemplatesTable_18(
          this,
          Invocation.getter(#taskTemplates),
        ),
      ) as _i8.$TaskTemplatesTable);

  @override
  _i8.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_19(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i8.$AppDatabaseManager);

  @override
  Iterable<_i7.TableInfo<_i7.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i7.TableInfo<_i7.Table, Object?>>[],
      ) as Iterable<_i7.TableInfo<_i7.Table, Object?>>);

  @override
  List<_i7.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i7.DatabaseSchemaEntity>[],
      ) as List<_i7.DatabaseSchemaEntity>);

  @override
  _i7.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_20(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i7.GeneratedDatabase);

  @override
  _i7.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_21(
          this,
          Invocation.getter(#options),
        ),
      ) as _i7.DriftDatabaseOptions);

  @override
  _i7.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_22(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i7.StreamQueryUpdateRules);

  @override
  _i7.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_23(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i7.DatabaseConnection);

  @override
  _i7.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i12.dummyValue<_i7.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i7.SqlTypes);

  @override
  _i7.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_24(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i7.QueryExecutor);

  @override
  _i9.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_25(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i9.StreamQueryStore);

  @override
  _i7.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_26(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i7.DatabaseConnectionUser);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, int>> getDatabaseStats() => (super.noSuchMethod(
        Invocation.method(
          #getDatabaseStats,
          [],
        ),
        returnValue: _i10.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i10.Future<Map<String, int>>);

  @override
  _i7.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_27(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i7.Migrator);

  @override
  _i10.Future<void> beforeOpen(
    _i7.QueryExecutor? executor,
    _i7.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Stream<List<Map<String, Object?>>> createStream(
          _i9.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i10.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i10.Stream<List<Map<String, Object?>>>);

  @override
  T alias<T, D>(
    _i7.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i12.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i7.TableInfo<_i7.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i7.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Stream<Set<_i7.TableUpdate>> tableUpdates(
          [_i7.TableUpdateQuery? query = const _i7.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i10.Stream<Set<_i7.TableUpdate>>.empty(),
      ) as _i10.Stream<Set<_i7.TableUpdate>>);

  @override
  _i10.Future<T> doWhenOpened<T>(
          _i10.FutureOr<T> Function(_i7.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i12.ifNotNull(
              _i12.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i7.InsertStatement<T, D> into<T extends _i7.Table, D>(
          _i7.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_29<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i7.InsertStatement<T, D>);

  @override
  _i7.UpdateStatement<Tbl, R> update<Tbl extends _i7.Table, R>(
          _i7.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_30<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i7.UpdateStatement<Tbl, R>);

  @override
  _i7.SimpleSelectStatement<T, R> select<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_31<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i7.SimpleSelectStatement<T, R>);

  @override
  _i7.JoinedSelectStatement<T, R> selectOnly<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_32<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i7.JoinedSelectStatement<T, R>);

  @override
  _i7.Selectable<_i7.TypedResult> selectExpressions(
          Iterable<_i7.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeSelectable_33<_i7.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i7.Selectable<_i7.TypedResult>);

  @override
  _i7.DeleteStatement<T, D> delete<T extends _i7.Table, D>(
          _i7.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_34<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i7.DeleteStatement<T, D>);

  @override
  _i10.Future<int> customUpdate(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<int> customInsert(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i7.QueryRow>> customWriteReturning(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.TableInfo<_i7.Table, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i10.Future<List<_i7.QueryRow>>.value(<_i7.QueryRow>[]),
      ) as _i10.Future<List<_i7.QueryRow>>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelect(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_33<_i7.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i7.Selectable<_i7.QueryRow>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelectQuery(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_33<_i7.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i7.Selectable<_i7.QueryRow>);

  @override
  _i10.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<T> transaction<T>(
    _i10.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i12.ifNotNull(
              _i12.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<T> exclusively<T>(_i10.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i12.ifNotNull(
              _i12.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i10.Future<T>.value(v),
            ) ??
            _FakeFuture_28<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i10.Future<T>);

  @override
  _i10.Future<void> batch(
          _i10.FutureOr<void> Function(_i7.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i7.GenerationContext $write(
    _i7.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_35(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i7.GenerationContext);

  @override
  _i7.GenerationContext $writeInsertable(
    _i7.TableInfo<_i7.Table, dynamic>? table,
    _i7.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_35(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i7.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}
